### ISSUE TITLE
首页数据解码错误造成闪退

### ISSUE THREAD

**Issue by stroyBoard** [Kuntanury/AnyKnew#1]
ERROR：“Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "alliter", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil)): file /Users/lanyu/Documents/Project/AnyKnew/Project/AnyKnew/Home/HomeViewController.swift, line 46”

**Comment by Kuntanury** [comment]
Fixed
